### ISSUE TITLE
FEAT - user profile api 

### ISSUE THREAD

**Issue by soyalattee** [pda-dongdonge/dongdong-back#8]
## 💡 Feature issue
- user의 followers ,following 관련 api 

## ✅ To-do
- [x] get 해당 유저 정보(아이디 조회 -> 닉네임 등 )
- [x] get 팔로잉 팔로워
- [x] get 좋아요한 버킷
- [x] get 해당 유저 버킷
- [x] post following 요청 /취소 
- [x] get follow 여부

**Comment by soyalattee** [comment]
유저 프로필 페이지 관련 api 개발 완료
